# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ull"
client_id = "efdf095a7c47c231f5319dfc2eba5517"
application_url = "https://soa-laughing-recognition-bears.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://soa-laughing-recognition-bears.trycloudflare.com/auth/callback",
  "https://soa-laughing-recognition-bears.trycloudflare.com/auth/shopify/callback",
  "https://soa-laughing-recognition-bears.trycloudflare.com/api/auth/callback",
  "https://soa-laughing-recognition-bears.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "oroa-development.myshopify.com"
